version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: tictactoe
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data/mongo:/data/db
  backend:
    build: ./backend
    container_name: api-eventos
    restart: always
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
